In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [2]:
# Load dataset
dataset = pd.read_csv('../dataset/diabetes_norm.csv')
dataset.head()

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.461538,0.670968,0.489796,0.000000,0.418478,0.396963,0.617021,1
1,0.076923,0.264516,0.428571,0.000000,0.228261,0.197397,0.212766,0
2,0.615385,0.896774,0.408163,0.000000,0.138587,0.429501,0.234043,1
3,0.076923,0.290323,0.428571,0.226506,0.269022,0.064353,0.000000,0
4,0.384615,0.464516,0.510204,0.000000,0.201087,0.088937,0.191489,0

In [3]:
dataset.describe()

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,688.000000,688.000000,688.000000,688.000000,688.000000,688.000000,688.000000,688.000000
mean,0.295841,0.492217,0.493326,0.174716,0.380684,0.272274,0.257329,0.329942
std,0.252250,0.193586,0.125641,0.217125,0.179861,0.205732,0.243340,0.470534
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.076923,0.354839,0.408163,0.000000,0.250000,0.120752,0.063830,0.000000
50%,0.230769,0.458065,0.489796,0.104819,0.375000,0.211135,0.170213,0.000000
75%,0.461538,0.612903,0.571429,0.303614,0.491848,0.381417,0.404255,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
## Missing Data Checking:
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
all_features = dataset.keys()
n_features = all_features[1:7]
label = all_features[7]

In [14]:
dat = dataset[n_features]
dat

,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.670968,0.489796,0.000000,0.418478,0.396963,0.617021
1,0.264516,0.428571,0.000000,0.228261,0.197397,0.212766
2,0.896774,0.408163,0.000000,0.138587,0.429501,0.234043
3,0.290323,0.428571,0.226506,0.269022,0.064353,0.000000
4,0.464516,0.510204,0.000000,0.201087,0.088937,0.191489
...,...,...,...,...,...,...
683,0.367742,0.530612,0.433735,0.399457,0.067245,0.893617
684,0.503226,0.469388,0.000000,0.505435,0.189443,0.127660
685,0.496774,0.489796,0.269880,0.217391,0.120752,0.191489
686,0.529032,0.367347,0.000000,0.323370,0.195951,0.553191
687,0.316129,0.469388,0.000000,0.331522,0.171367,0.042553

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dat, dataset[label].values, test_size=0.20, random_state=1)

In [17]:
# Train the SVC
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)

C:\Users\JosephQuang\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [18]:
# Prediction
predictions = model.predict(X_test)
print(predictions)

[0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0
 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1]

In [19]:
# Evaluations
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[88  5]
 [24 21]]

In [20]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.79      0.95      0.86        93
           1       0.81      0.47      0.59        45

    accuracy                           0.79       138
   macro avg       0.80      0.71      0.73       138
weighted avg       0.79      0.79      0.77       138